
spring:
  application:
    name: lab-4-adjective
  config:
    import: "optional:configserver:http://localhost:8001"
  profiles:
    active: adjective

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8010/eureka/

# words: reasonable,leaky,suspicious,ordinary,unlikely

server:
  port: ${PORT:${SERVER_PORT:0}}